channels:
  -
    id: purgers
    grants:
      - 0
      - 2
      - 3
  -
    id: queue
    grants:
      - 0
      - 2
      - 3
  -
    id: diagnostics
    grants:
      - 3
  -
    id: purger_acquia_purge_09327b515e
    grants:
      - 0
      - 2
      - 3
  -
    id: purger_dropsolid_purge_f4da2bd351
    grants:
      - 0
      - 2
      - 3
